# Generated by Django 3.2.4 on 2021-06-11 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='soccer_team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teamName', models.CharField(max_length=50)),
                ('ranking', models.IntegerField()),
                ('country', models.CharField(max_length=70)),
            ],
        ),
    ]
