# Generated by Django 3.2.4 on 2021-06-11 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_soccer_team'),
    ]

    operations = [
        migrations.CreateModel(
            name='To_do',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan', models.CharField(max_length=200)),
                ('due_date', models.DateTimeField(verbose_name='due date')),
                ('completed', models.BooleanField()),
            ],
        ),
        migrations.DeleteModel(
            name='idol_Group',
        ),
        migrations.DeleteModel(
            name='soccer_team',
        ),
    ]
